model_name: 'resnet50'

model_output_paths:
  dir: 'models'
  model: 'models/resnet50.pt'

hyperparameters:
  epochs: 100
  batch_size: 32
  learning_rate: 0.0001
  learning_rate_layer4: 0.000001
  lr_scheduler_patience: 5
  lr_threshold: 0.01
  patience: 10
  finetune_layers: ['layer4', 'fc']